= Lenald Ng Wai Jun - cherBook Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Introduction
cherBook is an address book application that combines statistical analysis with the ease of communication.
cherBook is targetted at teachers as it offers various functionalities that can improve the lives of teachers.

The user can interact with it using a command line interface, and it has a graphical user interface created with JavaFX.
The application is written in Java, and has about 8 thousand lines of code (kLoC).

*Code contributed*: [https://github.com/Lenaldnwj/main/blob/master/collated/main/Lenaldnwj.md[Functional code]] [https://github.com/Lenaldnwj/main/blob/master/collated/test/Lenaldnwj.md[Test code]]

=== Enhancement Added: Randomised Unique Tag Colors

==== External behavior

---

#Start of Extract [from: Developer Guide]#

include::../UserGuide.adoc[tag=randomisedUniqueTagColors]

#End of Extract#

---

==== Justification

In this day and age, educators have many classes of students to teach. They will have difficulty differentiating between
tags of different descriptions, if they are to tag many of their students.

This feature will assign tags of the same descriptions with a unique color. With the implementation of this feature,
 educators will be able to distinguish between the different tags easily.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=uniquetagcolor]

#End of Extract#

---


=== Enhancement Added: Optional Inputs/Fields

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=optionalinputtagstwo]

#End of Extract#

---

==== Justification

As we increased the number of attributes for the person who is being added into the address book, we realised that it is getting very cumbersome for the user to
input all the compulsory attributes into cherBook. Furthermore, the person to be added might not have all the attributes deemed compulsory.


Thus, we decided that several non essential attributes can
be optional inputs for the user.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=optionalInput]

#End of Extract#

---

=== Enhancement Added: Multiple Numbers (Parent and Student number)

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=optionalinputtagstwo]

#End of Extract#

---

==== Justification

Initially, cherBook had the option of only being able to record the student's number.
We decided to come out with multiple numbers (Parent and Student number)
as many educators believe that there needs to be good communication between not only the students, but their parents too.

This enhancement is especially useful for those who are in charge of younger students
in primary school. Educators in institution with younger students
will find having parents numbers more important than the student's number as there tends to be more communication
between the teachers and the parent of the students.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=studentparentcontact]

#End of Extract#

---

=== Enhancement Proposed: Add command `Study Buddy`

==== External behavior

==== Justification
==== Implementation


=== Other contributions


* Included ParentPhone attribute (Pull request https://github.com/CS2103AUG2017-T16-B2/main/pull/116[#116])
* Included icons in PersonListCard (Pull request https://github.com/CS2103AUG2017-T16-B2/main/pull/116[#116])
* Icon text descriptors in ExtendedPersonCard on startup of cherBook (Pull request https://github.com/CS2103AUG2017-T16-B2/main/pull/121[#121])
* Improve sample data (Pull requests https://github.com/CS2103AUG2017-T16-B2/main/pull/79[#79], https://github.com/CS2103AUG2017-T16-B2/main/pull/120[#120])
* Improve test quality of several features (Pull requests https://github.com/CS2103AUG2017-T16-B2/main/pull/88[#88]
, https://github.com/CS2103AUG2017-T16-B2/main/pull/113[#113], https://github.com/CS2103AUG2017-T16-B2/main/pull/121[#121])
* Remove unused codes to improve coveralls (Pull request https://github.com/CS2103AUG2017-T16-B2/main/pull/129[#129])

== Project: NUS Interactive Food Map

It is an interactive food map of the NUS campus that shows information of major food places in the nus map.
